<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<TUnitImplicitUsings>false</TUnitImplicitUsings>
		<TUnitAssertionsImplicitUsings>false</TUnitAssertionsImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
		<PackageReference Include="TUnit" Version="1.69.0" />
		<PackageReference Include="TUnit.AspNetCore" Version="1.69.0" />
		<PackageReference Include="TUnit.Mocks" Version="1.69.0" />
		<PackageReference Include="TUnit.Mocks.Assertions" Version="1.69.0" />
		<PackageReference Include="TUnit.Mocks.Logging" Version="1.69.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Services\UserService\UserService.Api\UserService.Api.csproj" />
		<ProjectReference Include="..\TestDoubles\TestDoubles.csproj" />
	</ItemGroup>

</Project>
